# docker/config/application.yml
server:
  port: 8030
  useTls: false

kafka:
  bootstrapServers: kafka:9092  # Internal Kafka address using PLAINTEXT listener
  mainTopic: monte-carlo-raw-events
  deadLetterTopic: monte-carlo-dead-letter

monitoring:
  enabled: true
  metricsPort: 8080

atlas:
  url: http://atlas:21000
  username: admin
  password: admin
